AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'
    - 'bin/rspec'
    - 'bin/rubocop'
    - 'bin/setup'
    - 'bin/cap'
    - 'bin/capify'
  DisplayCopNames: true
  DisplayStyleGuide: true

# Override default enabled cops

# Allow block comments
Style/BlockComments:
  Enabled: false

# Disable
Style/Documentation:
  Enabled: false

# Recheck this cop later
Style/DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  StyleGuide: '#consistent-multi-line-chains'
  Enabled: true

# Disable magic
Style/FrozenStringLiteralComment:
  Enabled: false

# Recheck this cop later
Style/FlipFlop:
  Description: 'Checks for flip flops'
  StyleGuide: '#no-flip-flops'
  Enabled: true

# Recheck this cop later
Style/RedundantException:
  Description: "Checks for an obsolete RuntimeException argument in raise/fail."
  StyleGuide: '#no-explicit-runtimeerror'
  Enabled: true

# Recheck this cop later
Style/SafeNavigation:
  Description: >-
                  This cop transforms usages of a method call safeguarded by
                  a check for the existance of the object to
                  safe navigation (`&.`).
  Enabled: true

# Recheck this cop later
Style/SignalException:
  Description: 'Checks for proper usage of fail and raise.'
  StyleGuide: '#prefer-raise-over-fail'
  Enabled: true


# Rails:
#   Enabled: true
#


