AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'
    - 'bin/rspec'
    - 'bin/rubocop'
    - 'bin/setup'
    - 'bin/cap'
    - 'bin/capify'
  DisplayCopNames: true
  DisplayStyleGuide: true

# Override default enabled cops

# Allow block comments
Style/BlockComments:
  Enabled: false

# Disable
Style/Documentation:
  Enabled: false

# Recheck this cop later
Style/DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  StyleGuide: '#consistent-multi-line-chains'
  Enabled: true

# Disable magic
Style/FrozenStringLiteralComment:
  Enabled: false

# Recheck this cop later
Style/FlipFlop:
  Description: 'Checks for flip flops'
  StyleGuide: '#no-flip-flops'
  Enabled: true


# Rails:
#   Enabled: true
#


